#!/bin/bash --login
SOURCE="${BASH_SOURCE[0]}"
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR

if [[ $1 == bybitu ]]; then
	$DIR/run.sh byb_ws.c usdt-ada@p usdt-xem@p usdt-bnb@p usdt-aave@p usdt-etc@p usdt-doge@p usdt-eos@p usdt-xrp@p usdt-matic@p usdt-xtz@p usdt-sol@p usdt-comp@p usdt-trx@p usdt-xlm@p usdt-theta@p usdt-avax@p usdt-algo@p usdt-sushi@p usdt-icp@p usdt-ftm@p usdt-atom@p usdt-dydx@p usdt-iost@p usdt-bit@p usdt-ftt@p usdt-link@p usdt-dash@p usdt-shib1000@p usdt-fil@p usdt-near@p usdt-hbar@p usdt-celr@p usdt-one@p usdt-c98@p usdt-alice@p usdt-ksm@p usdt-srm@p usdt-vet@p usdt-enj@p usdt-sand@p usdt-chz@p usdt-crv@p usdt-ltc@p usdt-dot@p usdt-mana@p usdt-gala@p usdt-ens@p usdt-woo@p usdt-iotx@p usdt-lrc@p usdt-chr@p usdt-slp@p usdt-keep@p usdt-tlm@p usdt-egld@p usdt-storj@p usdt-imx@p usdt-ankr@p usdt-flow@p usdt-bal@p usdt-uni@p usdt-ilv@p usdt-bat@p usdt-gtc@p usdt-lit@p usdt-rsr@p usdt-rndr@p usdt-cvc@p usdt-sc@p usdt-axs@p usdt-stx@p usdt-iota@p usdt-cro@p usdt-kava@p usdt-1inch@p usdt-dent@p usdt-audio@p usdt-waves@p usdt-cream@p usdt-ape@p usdt-coti@p usdt-sxp@p usdt-grt@p usdt-dusk@p usdt-knc@p usdt-kda@p usdt-anc@p usdt-hot@p usdt-zec@p usdt-rose@p usdt-celo@p usdt-zrx@p usdt-klay@p usdt-jst@p usdt-neo@p usdt-bsw@p usdt-bake@p usdt-glmr@p usdt-zil@p usdt-spell@p usdt-gmt@p usdt-astr@p usdt-jasmy@p usdt-fxs@p usdt-bnx@p usdt-1000btt@p usdt-cvx@p usdt-gal@p usdt-ar@p usdt-ren@p
elif [[ $1 == 'ftx' ]]; then
	$DIR/run.sh ftx_ws.c doge link ltc trx uni usdt-aave usdt-bal usd-ltc usd-1inch usd-cvc usd-aave usd-bal usd-bat usd-comp usd-link usd-storj usd-uni usd-zrx usd-ftt usd-fxs usdt-cream usdt-ftt usdt-avax usdt-comp usdt-doge usdt-eth usdt-ltc usdt-link usdt-trx usdt-uni usdt-xrp usd-trx usd-cro usd-boba usd-usdt usd-btt usd-ape usd-imx usd-gmt usd-slp usd-cream usd-sos usd-ksos xrp eth usdt-btc usd-btc usd-eth usd-xrp usd-doge usd-avax usd-atom usdt-atom usd-btc@p usd-bnb@p usd-ada@p usd-eth@p usd-neo@p usd-grt@p usd-imx@p usd-kshib@p usd-step usd-dent usd-cvc@p usd-xmr@p usd-stx@p usd-sc@p usd-1inch@p usd-axs@p usd-audio@p usd-celo@p usd-ltc@p usd-bat@p usd-ar@p usd-xlm@p usd-slp@p usd-algo@p usd-ren@p usd-icx@p usd-one@p usd-ftm@p usd-icp@p usd-comp@p usd-eos@p usd-doge@p usd-trx@p usd-matic@p usd-alcx@p usd-kava@p usd-rndr@p usd-clv@p usd-okb@p usd-scrt@p usd-uni@p usd-anc@p usd-rose@p usd-spell@p usd-gal@p usd-c98@p usd-hbar@p usd-dent@p usd-alice@p usd-enj@p usd-cro@p usd-flow@p usd-perp@p usd-flm@p usd-hnt@p usd-sand@p usd-chz@p usd-crv@p usd-dot@p usd-srm@p usd-ens@p usd-zec@p usd-chr@p usd-iotx@p usd-btt@p usd-kbtt@p usd-lrc@p usd-boba@p usd-tlm@p usd-gala@p usd-hot@p usd-reef@p usd-waves@p usd-cream@p usd-ape@p usd-sushi@p usd-knc@p usd-glmr@p usd-zil@p usd-jasmy@p usd-ksos@p usd-xtz@p usd-mana@p usd-egld@p usd-tru@p usd-agld@p usd-sol@p usd-vet@p usd-theta@p usd-badger@p usd-avax@p usd-fil@p usd-link@p usd-dydx@p usd-bit@p usd-near@p usd-aave@p usd-atom@p usd-storj@p usd-bal@p usd-iota@p usd-xem@p usd-zrx@p usd-pundix@p usd-xrp@p usd-rsr@p usd-dash@p usd-paxg@p usd-mina@p usd-sxp@p usd-gmt@p usd-fxs@p usd-cvx@p usd-step@p
else
	echo "Not supported $@"
	exit 1
fi
